### ISSUE TITLE
好多小问题？

### ISSUE THREAD

**Issue by dmhai** [Jimmey-Jiang/ABP-ASP.NET-Boilerplate-Project-CMS#3]
看起来框架不错，但是运行起来感觉不太靠谱，各种问题。。。。
首先，readme里面，打开方式第4点update database拼写不对，这导致无法生成数据库。
然后，就算修正了，可以生成数据库了，直接跑起来。403，手动导向登录，发现页面有JS错误，
输入用户名:admin 密码123qwe ，报错，无法登录。。。

**Comment by Jimmey-Jiang** [comment]
不会吧，我回头看一下，我本地都是跑通过了再放上去的，最好先包还原！
